### ISSUE TITLE
Remove the booking status exceptions in the conflict condition

### ISSUE THREAD

**Issue by mecha** [RebelCode/rcmod-eddbk-booking-logic#3]
Remove the explicit check for `approved` and `scheduled` status in the booking conflict validator. All bookings should conflict, with the exception of `in_cart`.

**Comment by markzahra** [comment]
I tested as follows:

There was an existing booking for a service with a specific start and end time.

I took another existing booking with a different service and specific start and end time. I edited this booking to match the exact details of the first existing booking (above), but chose an action for a different status. 

Upon saving changes, I was allowed to do so. The database now had two entries with the same service, same start and end timestamps, and different booking statuses, which should not be allowed.

**Comment by markzahra** [comment]
In Alpha 7, I was able to save a Draft booking and then Schedule a booking, for the same service, on the same day, at the same time, as seen in this screenshot.

<img width="1207" alt="screen shot 2018-06-06 at 21 23 05" src="https://user-images.githubusercontent.com/22813210/41060430-fe502e14-69cf-11e8-98ee-d7487a2c9b5f.png">

Is Draft treated the same as In Cart, and therefore, this behaviour is known and correct?

**Comment by mecha** [comment]
No, only the cart status is non-blocking. Every other status should prevent this. I will investigate.

**Comment by mecha** [comment]
@markzahra I cannot reproduce this.

**Comment by markzahra** [comment]
I can no longer reproduce.
